spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book-store
    username: postgres
    password: rasul96
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8088
